export const BRANCH_ROLE_CONTEXT_ZH: Record<string, string> = {
  "c2b-parachute": "你刚接任事业部，前任的两位核心经理还在观望，第一场会还没开。",
  "c2b-founder": "你刚拿到一笔过桥贷款，但正式融资还没有到账，团队里已经有人开始催工资。",
  "c2b-highPotential": "你被 CEO 点名牵头项目，但预算和人手都还在别的部门手里。",
  "c3b-parachute": "你拿到 30 人盘点表，财务建议先砍成本，老团队担心你拿名单立威。",
  "c3b-founder": "你的联合创始人掌握销售，但管理粗放；招来的新人已经开始质疑分工。",
  "c3b-highPotential": "你负责给跨部门项目排角色，两个负责人都不愿让出关键任务。",
  "c4b-parachute": "你推动的新流程刚发布三天，运营负责人就在走廊里和下属说“撑不过一个月”。",
  "c4b-founder": "联合创始人在全员会上反对新产品方向，两个团队已经开始按不同版本做事。",
  "c4b-highPotential": "你的跨部门方案被资深负责人挑出一个数据漏洞，对方在群里直接否定了整份方案。",
  "c5b-parachute": "CEO 给你定了收入翻倍目标，但财务给出的历史数据里，增长最快的一年也只有 40%。",
  "c5b-founder": "你定了季度增长目标，销售想先冲大客户，研发想先补产品缺口。",
  "c5b-highPotential": "跨部门小组的季度目标已经拆到个人，但有两个成员从不参加同步会。",
  "c6b-parachute": "CFO 和销售副总绕过你推进了一个大单，合同已经进入法务流程。",
  "c6b-founder": "合伙人把公司资源投进自己的新项目，你作为 CEO 却只看到月报里的摘要。",
  "c6b-highPotential": "高层直接给项目成员下达指令，成员开始绕过你确认优先级。",
  "c7b-parachute": "你出差一周，回来发现团队把三个月前废弃的流程重新用了起来。",
  "c7b-founder": "你病休两天，公司的报价和客户回复全部停滞，只有你一个人知道怎么处理。",
  "c7b-highPotential": "你休假一周，项目群静默了四天，因为所有关键判断都等你回来。",
  "c8b-parachute": "最大客户暂停付款，财务说下个月工资只够发六成，你只有 48 小时。",
  "c8b-founder": "最大客户暂停付款，账上现金只够一个月，两位合伙人开始讨论撤资。",
  "c8b-highPotential": "项目预算被砍 30%，供应商要求先付款再交货，团队在等你的新排期。",
  "c9b-parachute": "CEO 想让你进入更高层，但接班人的第一次独立决策还没完成。",
  "c9b-founder": "公司终于稳定，投资人邀请你去做更大平台，创始团队担心失去主心骨。",
  "c9b-highPotential": "你即将晋升，继任者刚接手两个关键客户，项目正处在交付节点。"
};

export const BRANCH_ROLE_CONTEXT_EN: Record<string, string> = {
  "c2b-parachute": "You have just taken over the division, and the predecessor's two core managers are still watching; the first all-hands has not happened yet.",
  "c2b-founder": "You just secured a bridge loan, but the formal round has not arrived and someone in the team is already asking about payroll.",
  "c2b-highPotential": "The CEO named you to lead the project, but the budget and people still belong to other departments.",
  "c3b-parachute": "You receive the 30-person roster; finance suggests cutting costs first, and the old team worries the list is about building loyalty.",
  "c3b-founder": "Your co-founder owns sales but manages loosely, and newly hired people have already started questioning the division of labor.",
  "c3b-highPotential": "You are assigning roles for a cross-department project, and two owners refuse to release the critical tasks.",
  "c4b-parachute": "Three days after the new process launches, the operations lead tells colleagues in the hallway that it will not survive a month.",
  "c4b-founder": "The co-founder publicly opposes the new product direction at the all-hands, and two teams have already begun building different versions.",
  "c4b-highPotential": "A senior lead finds a data gap in your cross-department proposal and rejects the entire plan in the group chat.",
  "c5b-parachute": "The CEO sets a revenue-doubling target, but finance shows that the best historical year grew only 40%.",
  "c5b-founder": "You set a quarterly growth target; sales wants to chase big accounts while engineering wants to close product gaps first.",
  "c5b-highPotential": "The cross-department quarterly goal has been split to individuals, but two members never attend the sync meetings.",
  "c6b-parachute": "The CFO and sales VP pushed a major deal around you, and the contract is already in legal review.",
  "c6b-founder": "A partner invests company resources into their own new project, and as CEO you only see a summary in the monthly report.",
  "c6b-highPotential": "Senior leadership gives direct instructions to project members, who begin bypassing you to confirm priorities.",
  "c7b-parachute": "After a week away, you return to find the team has revived a process abandoned three months ago.",
  "c7b-founder": "After two sick days, quoting and client replies stop completely because only you know how to handle them.",
  "c7b-highPotential": "After a week of leave, the project channel is silent for four days because every key judgment waits for your return.",
  "c8b-parachute": "The largest client freezes payment, finance says next month's payroll can only cover 60%, and you have 48 hours.",
  "c8b-founder": "The largest client freezes payment, cash covers one month, and two partners have begun discussing an exit.",
  "c8b-highPotential": "The project budget is cut by 30%, the supplier asks for payment before delivery, and the team waits for a new schedule.",
  "c9b-parachute": "The CEO wants you at a higher level, but your successor's first independent decision is not complete.",
  "c9b-founder": "The company has finally stabilized, an investor invites you to a bigger platform, and the founding team worries about losing its anchor.",
  "c9b-highPotential": "You are about to be promoted, your successor just took over two key clients, and the project is at a delivery node."
};
