import type { AcademyScenario } from "./team-academy";

export const HIGH_POTENTIAL_SCENARIOS: AcademyScenario[] = [
  {
    id: "h1",
    role: "highPotential",
    level: 1,
    title: "打杂任务",
    situation: "入职第一周被分配整理历史文档，预计两周。",
    options: ["按部就班完成", "高效完成并梳理关键决策点摘要", "找经理要求更有挑战的任务", "完成后再私下请教核心业务"],
    best: 1,
    feedback: "在基础任务上叠加思考动作，把琐事变成知识沉淀，是高潜的第一信号。",
    knowledge: "执行思维"
  },
  {
    id: "h2",
    role: "highPotential",
    level: 1,
    title: "同事被表扬",
    situation: "经理公开表扬同事的报告，但内容与你私下汇报高度相似。",
    options: ["当场补充我也做过", "私下找同事合并数据做完整版", "找经理确认我的贡献", "什么都不说"],
    best: 1,
    feedback: "把功劳竞争转化为成果合作，经理会注意到你的格局。",
    knowledge: "协作能力"
  },
  {
    id: "h3",
    role: "highPotential",
    level: 1,
    title: "经理方案有漏洞",
    situation: "你发现经理的技术方案存在重大风险，但团队都在点头。",
    options: ["会上直接指出", "会后私下用假设性语言反馈", "保持沉默", "会后找资深同事验证再反馈"],
    best: 1,
    feedback: "私下反馈风险、公开支持决策，是向上管理的黄金法则。",
    knowledge: "向上管理"
  },
  {
    id: "h4",
    role: "highPotential",
    level: 1,
    title: "非核心项目",
    situation: "核心项目给了资历更深的同事，你被分配小型维护项目。",
    options: ["接受并做到极致", "要求换核心项目", "维护之外增加系统优化建议", "快速做完去帮同事"],
    best: 2,
    feedback: "在非核心岗位上做出增值洞察，是高潜最突出的信号之一。",
    knowledge: "专业态度"
  },
  {
    id: "h5",
    role: "highPotential",
    level: 2,
    title: "成果被截胡",
    situation: "你两周做的分析被同事在周会展示，完全没有提你的贡献。",
    options: ["会后找经理确认是否有误解", "找同事直接对质", "沉默", "用更新版本重新展示"],
    best: 0,
    feedback: "温和主张功劳归属，用确认代替投诉，请经理校准认知。",
    knowledge: "可见度管理"
  },
  {
    id: "h6",
    role: "highPotential",
    level: 2,
    title: "团队协作低效",
    situation: "5人小组靠口头传达需求，信息经常丢失，每周都在对齐。",
    options: ["向经理建议建共享看板并负责搭建", "自己默默建看板", "不主动提", "先私下收集同事意见再提"],
    best: 0,
    feedback: "发现问题后主动提出方案并担责，而不是只把问题上交。",
    knowledge: "主动性"
  },
  {
    id: "h7",
    role: "highPotential",
    level: 2,
    title: "被经理忽视",
    situation: "最近经理分配重要任务总绕过你，周会互动明显减少。",
    options: ["主动约1对1请求反馈", "更努力工作", "找资深同事打听", "不主动追问"],
    best: 0,
    feedback: "主动争取反馈，减少不确定性，是被冷落时最职业的回应。",
    knowledge: "自我管理"
  },
  {
    id: "h8",
    role: "highPotential",
    level: 2,
    title: "经理决策引发不满",
    situation: "经理快速决策的风格让几位同事不满，但没有公开表达。",
    options: ["不干预", "会后私下提供补充分析", "和同事形成共识再提", "直接告诉经理大家的不满"],
    best: 1,
    feedback: "把情绪翻译成事实和方案，帮助经理做更完整的决策。",
    knowledge: "向上反馈"
  },
  {
    id: "h9",
    role: "highPotential",
    level: 3,
    title: "经理抢了汇报机会",
    situation: "你花一周做数据分析和PPT，汇报由经理完成，高层夸奖数据扎实。",
    options: ["会后提出补充要点纪要", "什么都不说", "在高层面前补充是我做的", "会后私下找高层展示"],
    best: 0,
    feedback: "让上级在舞台上表现更好，你的价值会自然被看见。",
    knowledge: "向上管理"
  },
  {
    id: "h10",
    role: "highPotential",
    level: 3,
    title: "资深同事否定方案",
    situation: "评审会上资深同事凭经验否定你的方案，但没给具体依据。",
    options: ["放弃方案", "公开追问失败原因", "会后完善证据再沟通", "会后约咖啡请教"],
    best: 2,
    feedback: "用行动和数据说服，而不是公开辩论，既能赢方案也能赢得尊重。",
    knowledge: "影响力"
  },
  {
    id: "h11",
    role: "highPotential",
    level: 3,
    title: "客户直接表扬你",
    situation: "客户当众说你的分析比以往都深入，经理微笑没有回应。",
    options: ["归功于团队并请求继续深挖", "直接问能否继续做", "什么都不说", "周会上主动分享"],
    best: 0,
    feedback: "把正反馈转化为资源和授权，同时把功劳归于团队。",
    knowledge: "可见度管理"
  },
  {
    id: "h12",
    role: "highPotential",
    level: 3,
    title: "工作边界模糊",
    situation: "你的工作内容不断扩宽，职位和薪资没有变化。",
    options: ["全部接受", "找经理确认职责定位和发展关联", "直接拒绝非核心工作", "默默记录等绩效评估"],
    best: 1,
    feedback: "边界管理是管理能力的一部分，确认为什么做和做多久。",
    knowledge: "职业化管理"
  },
  {
    id: "h13",
    role: "highPotential",
    level: 4,
    title: "没有成功标准的任务",
    situation: "经理让你研究AI应用前景，两周后给初步判断，没有明确要求。",
    options: ["按自己理解交报告", "先反问关注技术还是商业", "先给初步框架确认", "直接做深度报告"],
    best: 2,
    feedback: "在模糊任务中先澄清预期，主动定义任务结构。",
    knowledge: "主动性"
  },
  {
    id: "h14",
    role: "highPotential",
    level: 4,
    title: "高调竞争者",
    situation: "同事小王很会展示成果，经理明显更多采纳他的意见。",
    options: ["模仿他的高调风格", "保持自己的风格", "增加结构化周同步", "找经理谈和小王对比"],
    best: 2,
    feedback: "找到适合自己的能见度方式，有节奏的书面同步是内向者的杠杆。",
    knowledge: "自我认知"
  },
  {
    id: "h15",
    role: "highPotential",
    level: 4,
    title: "高潜培养项目",
    situation: "你被选入公司高潜培养项目，担心影响当前业务产出。",
    options: ["全身心投入项目", "以业务为主", "和经理确认时间平衡", "主动争取高可见度角色"],
    best: 2,
    feedback: "提前管理时间边界，既展示责任感又保住业务贡献。",
    knowledge: "发展管理"
  },
  {
    id: "h16",
    role: "highPotential",
    level: 4,
    title: "导师与经理方向不一致",
    situation: "导师建议轮岗产品，经理希望深耕技术。",
    options: ["听导师的", "听经理的", "向导师提出先交付再转视角", "组织三方对话"],
    best: 2,
    feedback: "整合不同建议成阶段性路径，而不是选边站。",
    knowledge: "职业规划"
  },
  {
    id: "h17",
    role: "highPotential",
    level: 5,
    title: "新经理空降",
    situation: "信任的经理被调走，新经理带了自己的老部下过来。",
    options: ["主动约1对1介绍自己", "先观望", "用成果等新经理找你", "先找老部下建立关系"],
    best: 0,
    feedback: "空降期是信任窗口，谁先建立直接连接谁获得先发优势。",
    knowledge: "向上管理"
  },
  {
    id: "h18",
    role: "highPotential",
    level: 5,
    title: "无头衔项目负责人",
    situation: "你被指定牵头跨职能项目，但两位资深同事不太买账。",
    options: ["向经理要正式授权", "启动会书面分工并公开同步", "让出专业决策换取配合", "做甘特图发全员"],
    best: 1,
    feedback: "没有权力时，用信息透明和共同承诺推动执行。",
    knowledge: "横向影响力"
  },
  {
    id: "h19",
    role: "highPotential",
    level: 5,
    title: "建议执行不佳",
    situation: "你建议的新规范执行后效率下降，团队反馈成本太高。",
    options: ["主动向经理报告并给优化方向", "坚持改革有阵痛", "私下调整不告知经理", "等团队适应"],
    best: 0,
    feedback: "主动报告坏消息并带方案，是建立信任的证据。",
    knowledge: "责任担当"
  },
  {
    id: "h20",
    role: "highPotential",
    level: 5,
    title: "同事获得晋升",
    situation: "同期同事晋升，你觉得成果不差但名单里没有你。",
    options: ["约经理请教差距", "加倍努力工作", "只祝贺同事", "考虑外部机会"],
    best: 0,
    feedback: "把晋升失利转化为可执行的改进清单。",
    knowledge: "自我管理"
  },
  {
    id: "h21",
    role: "highPotential",
    level: 6,
    title: "辅导新人",
    situation: "经理让你带新人小林，本职工作已经很饱和。",
    options: ["最低限度辅导", "向经理请求资源调整", "制定3个月成长计划并1对1", "推给老刘"],
    best: 2,
    feedback: "带人的价值在于可衡量的成长结果，这是管理潜质的证据。",
    knowledge: "管理潜质"
  },
  {
    id: "h22",
    role: "highPotential",
    level: 6,
    title: "跨部门资源争夺",
    situation: "市场部说资源已投其他项目，但你的项目不能等。",
    options: ["向经理报告卡住", "提出每周2小时折中方案", "切出最小依赖项推进", "找高层协调"],
    best: 2,
    feedback: "精确切割依赖项，把资源争夺变成精准协作。",
    knowledge: "跨部门协作"
  },
  {
    id: "h23",
    role: "highPotential",
    level: 6,
    title: "流程优化被否",
    situation: "你提议优化流程提升20%效率，经理说现在没时间。",
    options: ["接受决定", "私下拉同事试点", "先用自己的小任务试跑", "整理详细方案再提"],
    best: 2,
    feedback: "用最小成本验证变革，可行性比完美性更重要。",
    knowledge: "推动变革"
  },
  {
    id: "h24",
    role: "highPotential",
    level: 6,
    title: "信息不足时决策",
    situation: "经理要你今天下班前定方向，你只有60%信息。",
    options: ["基于现有信息判断并标注边界", "要求再等24小时", "判断并建议小范围试点", "要求延后或容错空间"],
    best: 2,
    feedback: "在不确定中做出有依据的判断，并用低成本试点降低风险。",
    knowledge: "决策能力"
  },
  {
    id: "h25",
    role: "highPotential",
    level: 7,
    title: "对岗位失去热情",
    situation: "你越来越对产品策略感兴趣，但怕经理觉得你不专注。",
    options: ["隐藏变化", "1对1坦诚表达兴趣", "业余自学等有成果再谈", "直接申请跨部门项目"],
    best: 1,
    feedback: "坦诚表达兴趣变化，帮助组织看到真实你并调整路径。",
    knowledge: "自我认知"
  },
  {
    id: "h26",
    role: "highPotential",
    level: 7,
    title: "高风险创新项目",
    situation: "公司邀请你加入可能被叫停的内部创新项目。",
    options: ["all in", "拒绝冒险", "接受但约定40%时间投入", "先了解再决定"],
    best: 2,
    feedback: "有边界的冒险：参与但不离开，投入但不放弃。",
    knowledge: "风险决策"
  },
  {
    id: "h27",
    role: "highPotential",
    level: 7,
    title: "超高难度任务",
    situation: "经理说任务很难，做不成也理解，成功概率极低。",
    options: ["接受硬扛", "坦承能力边界", "接受并提出所需支持", "接受并独立推进"],
    best: 2,
    feedback: "接受任务时主动管理完成条件，坦承边界也是职业化。",
    knowledge: "自我认知"
  },
  {
    id: "h28",
    role: "highPotential",
    level: 7,
    title: "高潜标签被疏远",
    situation: "被选入高潜项目后，同事开始与你保持距离。",
    options: ["不在意", "增加非正式互动", "复盘会主动分享真实盲区", "刻意表现低级错误"],
    best: 2,
    feedback: "用真实示弱平衡高潜身份，一致性是信任的基础。",
    knowledge: "关系管理"
  },
  {
    id: "h29",
    role: "highPotential",
    level: 8,
    title: "晋升需等待",
    situation: "经理说你今年被提名但名额不够，需要再等6个月。",
    options: ["被动等待", "问清楚差距并制定计划", "找外部机会", "请经理安排临时负责人"],
    best: 1,
    feedback: "把等待期变成准备期，针对评审差距补证据。",
    knowledge: "发展管理"
  },
  {
    id: "h30",
    role: "highPotential",
    level: 8,
    title: "为他人做嫁衣",
    situation: "经理让你帮老张准备汇报数据，荣誉不归你。",
    options: ["接受并做好", "接受并争取支持角色空间", "私下告诉老张可补充", "拒绝"],
    best: 1,
    feedback: "支持他人的同时保持可见度，让经理知道你的参与。",
    knowledge: "协作能力"
  },
  {
    id: "h31",
    role: "highPotential",
    level: 8,
    title: "模糊晋升信号",
    situation: "经理说你应该开始为下一级别做准备，但没有具体清单。",
    options: ["默默学习", "1对1追问具体差距", "盲目承担额外任务", "当鼓励不当承诺"],
    best: 1,
    feedback: "把模糊信号转化为具体行动，问清差距比问时间更有用。",
    knowledge: "向上管理"
  },
  {
    id: "h32",
    role: "highPotential",
    level: 8,
    title: "功劳被同事冒认",
    situation: "你设计的数据模型被同事在高层汇报时称为自己做的。",
    options: ["私下找同事确认", "直接找经理确认归属", "沉默", "在团队会暗示自己是设计者"],
    best: 0,
    feedback: "先同事后经理，温和但明确地维护贡献归属。",
    knowledge: "可见度管理"
  },
  {
    id: "h33",
    role: "highPotential",
    level: 9,
    title: "不认可的项目决策",
    situation: "团队正在推进你认为方向有误的方案，你是参与者。",
    options: ["公开反对", "会后私下找负责人讨论假设", "保持沉默", "会后给经理写邮件"],
    best: 1,
    feedback: "在决策前用风险提示影响决策，而不是事后质疑。",
    knowledge: "影响力"
  },
  {
    id: "h34",
    role: "highPotential",
    level: 9,
    title: "带问题实习生",
    situation: "实习生连续迟到、不按时交付，沟通几次态度敷衍。",
    options: ["向经理同步并请求边界确认", "自己无限耐心带", "只给数据不问判断", "直接警告不合格"],
    best: 0,
    feedback: "承担责任的同时向上管理预期，让解决路径被组织认可。",
    knowledge: "责任管理"
  },
  {
    id: "h35",
    role: "highPotential",
    level: 9,
    title: "第一次带团队",
    situation: "晋升为团队负责人，面对从同事到上级的关系转变。",
    options: ["强调和以前一样", "第一次会议宣布管理理念", "先观察三周不表态", "坦诚第一次带团队并请求反馈"],
    best: 3,
    feedback: "承认正在学习的状态比表演权威更能赢得团队支持。",
    knowledge: "领导力转型"
  },
  {
    id: "h36",
    role: "highPotential",
    level: 9,
    title: "资深成员公开质疑",
    situation: "你推行新管理方式，资深成员当众说这方法行不通。",
    options: ["邀请他做风险识别者", "当场请教怎么做", "坚持方案并忽略反馈", "会后调整但不公开说明"],
    best: 0,
    feedback: "倾听而不让步，把公开质疑转化为执行保障。",
    knowledge: "领导力试炼"
  }
];
