import type { AcademyScenario } from "./team-academy";

export const FOUNDER_SCENARIOS: AcademyScenario[] = [
  {
    id: "f1",
    role: "founder",
    level: 1,
    title: "定团队目标",
    situation: "你刚开始创业，团队成员还不清楚要一起解决什么问题，目标模糊。",
    options: ["先招人再定目标", "先和团队对齐客户问题与目标", "模仿竞品", "等融资到位再谈"],
    best: 1,
    feedback: "团队管理先从对齐目标和分工开始，目标不清再多人也跑不动。",
    knowledge: "团队目标"
  },
  {
    id: "f2",
    role: "founder",
    level: 1,
    title: "招募第一人",
    situation: "你要招第一个成员，候选人能力很强但要求高薪加股权。",
    options: ["直接答应", "评估长期承诺和价值观一致性", "只谈工资", "先画饼"],
    best: 1,
    feedback: "早期团队靠价值观和能力互补，而不是单一薪酬。",
    knowledge: "核心圈"
  },
  {
    id: "f3",
    role: "founder",
    level: 1,
    title: "资深成员",
    situation: "你招到一位经验比你丰富的成员，他开始挑战你的决策。",
    options: ["压制他", "把挑战当信息并共同验证", "让他走", "凡事听他的"],
    best: 1,
    feedback: "把资历差异转化为验证机制，而不是权力斗争。",
    knowledge: "影响力"
  },
  {
    id: "f4",
    role: "founder",
    level: 1,
    title: "决策瓶颈",
    situation: "所有关键决策都等你拍板，团队开始停下来等指令。",
    options: ["继续自己决策", "建立授权阶梯和决策边界", "让团队猜", "减少决策频率"],
    best: 1,
    feedback: "早期就要建立授权习惯，否则你永远是瓶颈。",
    knowledge: "授权"
  },
  {
    id: "f5",
    role: "founder",
    level: 2,
    title: "讲不清愿景",
    situation: "你觉得自己方向很清楚，但团队问你为什么时说不出来。",
    options: ["让团队执行就好", "把愿景讲成客户问题和三年目标", "抄行业口号", "先不说"],
    best: 1,
    feedback: "愿景要能翻译成大家为什么要做这件事。",
    knowledge: "导航"
  },
  {
    id: "f6",
    role: "founder",
    level: 2,
    title: "资源只够一个方向",
    situation: "两个方向都想做，但资源只够做一个。",
    options: ["都做一点", "用不做哪件损失最大排序", "问投资人", "抽签"],
    best: 1,
    feedback: "取舍靠损失最大原则，而不是兴趣。",
    knowledge: "优先次序"
  },
  {
    id: "f7",
    role: "founder",
    level: 2,
    title: "产品方向被质疑",
    situation: "团队认为你的产品方向有问题，并提出了替代方案。",
    options: ["坚持己见", "把两个方向做成可验证假设", "立刻换方向", "让团队投票"],
    best: 1,
    feedback: "用最小验证代替争论，让数据说话。",
    knowledge: "直觉法则"
  },
  {
    id: "f8",
    role: "founder",
    level: 2,
    title: "竞品快速迭代",
    situation: "竞品一个月发了三个版本，团队开始焦虑。",
    options: ["追每个功能", "守住核心用户价值和节奏", "加班追赶", "向竞品学习但无计划"],
    best: 1,
    feedback: "不要被竞品节奏带偏，先守住客户价值。",
    knowledge: "导航"
  },
  {
    id: "f9",
    role: "founder",
    level: 3,
    title: "团队没激情",
    situation: "团队开始机械执行，不再主动提想法。",
    options: ["加奖金", "给自主专精目的", "开会施压", "换人"],
    best: 1,
    feedback: "驱动力3.0：自主、专精、目的。",
    knowledge: "驱动力"
  },
  {
    id: "f10",
    role: "founder",
    level: 3,
    title: "给钱也留不住人",
    situation: "核心成员想离开，理由是看不到成长。",
    options: ["加薪", "了解真实原因并设计成长路径", "签竞业", "直接放人"],
    best: 1,
    feedback: "成长和意义感往往比薪资更关键。",
    knowledge: "人才保留"
  },
  {
    id: "f11",
    role: "founder",
    level: 3,
    title: "目标混乱",
    situation: "团队每周都在做不同的事，感觉忙但没有成果。",
    options: ["继续忙", "定3个要务和可量化KR", "让每个人自定目标", "砍掉所有目标"],
    best: 1,
    feedback: "目标要聚焦和可量化，才能对齐。",
    knowledge: "OKR"
  },
  {
    id: "f12",
    role: "founder",
    level: 3,
    title: "成员自己做了决定",
    situation: "一名成员未经授权做了一个重要决定，结果还行。",
    options: ["批评他越权", "肯定结果并确认下次边界", "默许", "公开表扬"],
    best: 1,
    feedback: "授权边界需要明确，但也要鼓励主动性。",
    knowledge: "授权"
  },
  {
    id: "f13",
    role: "founder",
    level: 4,
    title: "第一次授权失败",
    situation: "你授权骨干负责项目，他犯了一个可挽回但明显的错。",
    options: ["收回授权", "复盘原因并继续培养", "公开批评", "让他写检讨"],
    best: 1,
    feedback: "授权需要安全失败空间，复盘比惩罚重要。",
    knowledge: "授权阶梯"
  },
  {
    id: "f14",
    role: "founder",
    level: 4,
    title: "你亲自做所有事",
    situation: "产品、销售、客服都靠你，你开始没有时间思考。",
    options: ["继续扛", "列出可授权清单并逐步移交", "招人但不管", "减少业务"],
    best: 1,
    feedback: "把只有你能做的事拆解，先授权30%。",
    knowledge: "管理杠杆率"
  },
  {
    id: "f15",
    role: "founder",
    level: 4,
    title: "成员要求股权",
    situation: "早期成员要求更多股权，认为贡献被低估。",
    options: ["直接拒绝", "用贡献和未来承诺重谈", "答应所有要求", "让他走"],
    best: 1,
    feedback: "股权要基于贡献、阶段和承诺来谈，不能只靠情绪。",
    knowledge: "核心圈"
  },
  {
    id: "f16",
    role: "founder",
    level: 4,
    title: "客户需求多变",
    situation: "客户频繁改需求，团队疲于应付。",
    options: ["全部照做", "建立需求分级和变更机制", "拒绝所有变更", "让销售背锅"],
    best: 1,
    feedback: "用机制管理需求，而不是靠情绪。",
    knowledge: "优先次序"
  },
  {
    id: "f17",
    role: "founder",
    level: 5,
    title: "现金流危机下稳住团队",
    situation: "公司现金流紧张，团队人心浮动，担心裁员，交付开始受影响。",
    options: ["隐瞒团队", "公开事实并一起降本保命", "立刻裁员", "找高利贷"],
    best: 1,
    feedback: "危机时透明沟通并共同决策，比隐瞒更稳。",
    knowledge: "危机管理"
  },
  {
    id: "f18",
    role: "founder",
    level: 5,
    title: "士气低落",
    situation: "连续失败后团队士气很低，开始互相甩锅。",
    options: ["开检讨会追责", "先复盘系统再复盘人", "给团队打鸡血", "忽略"],
    best: 1,
    feedback: "先解决系统问题，再谈个人责任。",
    knowledge: "团队协作"
  },
  {
    id: "f19",
    role: "founder",
    level: 5,
    title: "合伙人理念冲突",
    situation: "两位合伙人一个要快扩张，一个要稳现金流。",
    options: ["选边站", "把两种目标做成可量化假设", "让董事会裁决", "各干各的"],
    best: 1,
    feedback: "用数据和验证化解理念冲突，而不是立场。",
    knowledge: "决策"
  },
  {
    id: "f20",
    role: "founder",
    level: 5,
    title: "招高管",
    situation: "公司要招第一位高管，你担心他抢走控制权。",
    options: ["只招听话的人", "招能力互补并明确授权边界", "不招", "让他负责全部"],
    best: 1,
    feedback: "高管要能补短板，边界靠机制不靠控制欲。",
    knowledge: "授权"
  },
  {
    id: "f21",
    role: "founder",
    level: 6,
    title: "老员工排挤新人",
    situation: "老员工认为新人抢了资源和功劳，团队出现小团体。",
    options: ["偏袒老人", "重新定义共同目标和分工", "开除老人", "让新人忍"],
    best: 1,
    feedback: "用共同目标和透明分工打破小团体。",
    knowledge: "团队协作"
  },
  {
    id: "f22",
    role: "founder",
    level: 6,
    title: "跨部门协作难",
    situation: "产品、技术、销售各说各话，信息不同步。",
    options: ["继续开会", "建立共享目标和依赖清单", "让CEO拍板", "各做各的"],
    best: 1,
    feedback: "把依赖关系变得可见，是协作的关键。",
    knowledge: "赋能"
  },
  {
    id: "f23",
    role: "founder",
    level: 6,
    title: "远程团队不同步",
    situation: "远程成员经常错过信息，进度不可见。",
    options: ["要求每天汇报", "建立异步文档和同步节奏", "取消远程", "靠自觉"],
    best: 1,
    feedback: "用透明文档和固定节奏替代控制。",
    knowledge: "共享意识"
  },
  {
    id: "f24",
    role: "founder",
    level: 6,
    title: "被迫裁员",
    situation: "现金流吃紧，必须裁掉一部分人。",
    options: ["按名单执行", "先按业务优先级决定保留谁", "让HR背锅", "拖着不裁"],
    best: 1,
    feedback: "裁员要基于业务优先级，而不是人情。",
    knowledge: "组织决策"
  },
  {
    id: "f25",
    role: "founder",
    level: 7,
    title: "文化失控",
    situation: "团队越来越大，你发现价值观开始被稀释。",
    options: ["只靠制度", "把价值观变成行为标准和复盘项", "不管", "开除不符合的人"],
    best: 1,
    feedback: "文化要靠可观察行为来维护，而不是口号。",
    knowledge: "文化建设"
  },
  {
    id: "f26",
    role: "founder",
    level: 7,
    title: "高潜成员挑战",
    situation: "你培养的骨干开始质疑你的方向，团队在围观。",
    options: ["压制他", "邀请他参与验证并明确边界", "让他走", "让步"],
    best: 1,
    feedback: "把挑战变成共同验证，展示倾听而不让步。",
    knowledge: "领导力试炼"
  },
  {
    id: "f27",
    role: "founder",
    level: 7,
    title: "培养接班人",
    situation: "你意识到公司离开你无法运转，决定培养接班人。",
    options: ["先培养追随者", "选2-3名高潜给完整项目", "等公司成熟再说", "自己继续扛"],
    best: 1,
    feedback: "培养领导者才能实现倍增。",
    knowledge: "爆炸性倍增"
  },
  {
    id: "f28",
    role: "founder",
    level: 7,
    title: "接班人犯错",
    situation: "你授权的接班人做了一个大决策，结果损失不小。",
    options: ["收回所有授权", "复盘系统并继续培养", "公开批评", "让他离职"],
    best: 1,
    feedback: "控制损失范围，把错误变成成长材料。",
    knowledge: "授权管理"
  },
  {
    id: "f29",
    role: "founder",
    level: 8,
    title: "离开一个月",
    situation: "你计划离开公司一个月，团队第一次独立运转。",
    options: ["远程遥控每件事", "提前授权并约定决策边界", "不离开", "让成员自行处理"],
    best: 1,
    feedback: "用机制保证组织离开你也能运转。",
    knowledge: "传承"
  },
  {
    id: "f30",
    role: "founder",
    level: 8,
    title: "为团队争取资源",
    situation: "董事会要求汇报团队进展，但团队需要更多资源才能完成目标。",
    options: ["讲愿景", "用团队具体结果和里程碑争取资源", "画饼", "让CFO代答"],
    best: 1,
    feedback: "用可验证的团队成果争取资源，而不是空谈。",
    knowledge: "团队资源"
  },
  {
    id: "f31",
    role: "founder",
    level: 8,
    title: "团队提新方向",
    situation: "团队提出一个新业务方向，和当前主业不同。",
    options: ["直接拒绝", "用最小验证判断是否试跑", "立刻投入", "让团队自己决定"],
    best: 1,
    feedback: "新方向要用低成本验证，而不是拍脑袋。",
    knowledge: "机会判断"
  },
  {
    id: "f32",
    role: "founder",
    level: 8,
    title: "大客户要求团队改方向",
    situation: "大客户要求团队放弃长期目标去赚快钱，团队开始摇摆。",
    options: ["接受", "评估对团队长期目标的影响并沟通取舍", "直接拒绝", "先签再说"],
    best: 1,
    feedback: "团队管理要守住长期目标，同时用取舍机制沟通。",
    knowledge: "团队取舍"
  },
  {
    id: "f33",
    role: "founder",
    level: 9,
    title: "你还在做所有决定",
    situation: "公司已经50人，但你还在审批每个细节。",
    options: ["继续审批", "建立授权层级和例外规则", "全部放权", "招聘更多助理"],
    best: 1,
    feedback: "组织规模越大，越需要机制代替个人。",
    knowledge: "赋能"
  },
  {
    id: "f34",
    role: "founder",
    level: 9,
    title: "计划不执行",
    situation: "团队同意了计划，但执行时总打折扣。",
    options: ["批评执行力", "检查目标是否对齐、KR是否可量化", "换人", "每天催"],
    best: 1,
    feedback: "执行偏差往往来自目标不清晰，而不是态度。",
    knowledge: "OKR"
  },
  {
    id: "f35",
    role: "founder",
    level: 9,
    title: "准备扩张",
    situation: "公司准备进入新市场，团队需要快速复制能力。",
    options: ["招更多执行者", "培养可独立带队的管理者", "自己先跑通", "外包"],
    best: 1,
    feedback: "扩张靠可复制的人才和组织能力。",
    knowledge: "爆炸性倍增"
  },
  {
    id: "f36",
    role: "founder",
    level: 9,
    title: "把公司交给下一任",
    situation: "你计划退居二线，需要确保公司价值观和管理体系延续。",
    options: ["直接交接", "培养接班团队并做传承演练", "保留关键决策权", "让董事会指定"],
    best: 1,
    feedback: "传承要把人和机制一起交出去。",
    knowledge: "传承法则"
  }
];
