import type { AcademyScenario } from "./team-academy";

export const PARACHUTE_SCENARIOS: AcademyScenario[] = [
  {
    id: "p1",
    role: "parachute",
    level: 1,
    title: "空降第一天",
    situation: "你空降为部门负责人，前任领导正式变成你的下属，交接只有十分钟。",
    options: ["马上宣布新制度", "先单独请前任吃饭并说明补位而非推翻", "让团队先自我汇报", "找上级要更大授权"],
    best: 1,
    feedback: "先稳住前任，等于稳住团队信息源头。",
    knowledge: "信任窗口"
  },
  {
    id: "p2",
    role: "parachute",
    level: 1,
    title: "前任沉默",
    situation: "部门会上前任不再发言，团队都在看你的反应。",
    options: ["忽略他直接推进", "公开把话题交给他并肯定经验", "会后批评他不配合", "向上级汇报"],
    best: 1,
    feedback: "公开保留前任的专业权威，把他变成军师而非地雷。",
    knowledge: "关系倒挂"
  },
  {
    id: "p3",
    role: "parachute",
    level: 1,
    title: "团队观望",
    situation: "团队表面配合，实际在等你的管理风格和边界。",
    options: ["立刻立规矩", "先观察30天并画团队地图", "模仿前任风格", "只和亲信建立关系"],
    best: 1,
    feedback: "前30天只观察不动刀，先建立信任地图。",
    knowledge: "观察期"
  },
  {
    id: "p4",
    role: "parachute",
    level: 1,
    title: "90天计划",
    situation: "上级要求你3个月内拿出梯队建设进展，但没有具体标准。",
    options: ["先承诺大目标", "先澄清成功标准再拆计划", "等数据齐了再说", "把任务分给下属"],
    best: 1,
    feedback: "模糊任务先澄清预期，再拆成30/60/90天计划。",
    knowledge: "预期管理"
  },
  {
    id: "p5",
    role: "parachute",
    level: 2,
    title: "技术债务",
    situation: "Review发现团队近半年存在多处技术债和性能瓶颈。",
    options: ["在周会点名批评", "组织不带批判的技术复盘", "自己偷偷修掉", "写邮件让团队整改"],
    best: 1,
    feedback: "用技术诊断和复盘破冰，把问题变成可复现的改进。",
    knowledge: "管理杠杆率"
  },
  {
    id: "p6",
    role: "parachute",
    level: 2,
    title: "旧流程抵制",
    situation: "你提议优化流程，团队说以前试过都失败。",
    options: ["强行推行", "先用一个小任务试跑验证", "放弃提议", "让老员工负责新流程"],
    best: 1,
    feedback: "用最小成本试点证明价值，不增加额外工作量。",
    knowledge: "推动变革"
  },
  {
    id: "p7",
    role: "parachute",
    level: 2,
    title: "老员工质疑",
    situation: "技术老员工公开质疑你的方案，认为不如旧方案。",
    options: ["现场辩论", "会后收集证据并请教他的具体案例", "直接采纳他的意见", "把他调离关键项目"],
    best: 1,
    feedback: "用行动和数据说服，而不是公开辩论。",
    knowledge: "影响力"
  },
  {
    id: "p8",
    role: "parachute",
    level: 2,
    title: "信息失真",
    situation: "需求靠口头传递，跨组协作频繁出现信息变形。",
    options: ["继续口头同步", "先向上确认优化方向再建看板", "自己偷偷建工具", "让每个组自己记录"],
    best: 1,
    feedback: "先对齐认知再落地工具，让改变在边界内运作。",
    knowledge: "主动方案"
  },
  {
    id: "p9",
    role: "parachute",
    level: 3,
    title: "坏消息",
    situation: "下属汇报项目可能延期，语气含糊，怕你发火。",
    options: ["立刻批评", "把话听完再问原因和下一步", "直接给方案", "让他写检讨"],
    best: 1,
    feedback: "先听完，再把情绪翻译成事实与下一步。",
    knowledge: "高质沟通"
  },
  {
    id: "p10",
    role: "parachute",
    level: 3,
    title: "问题抛回",
    situation: "下属遇到困难就把问题原样抛给你，等你决策。",
    options: ["自己解决", "问他自己有什么方案再讨论", "批评他不动脑", "换人处理"],
    best: 1,
    feedback: "教练式提问让下属自己说出答案，执行力完全不同。",
    knowledge: "教练式管理"
  },
  {
    id: "p11",
    role: "parachute",
    level: 3,
    title: "团队没激情",
    situation: "团队推一下动一下，给奖金也只有短期效果。",
    options: ["加大奖惩", "设计自主专精目的", "增加团建", "换血"],
    best: 1,
    feedback: "驱动力3.0：自主、专精、目的比胡萝卜加大棒更持久。",
    knowledge: "驱动力"
  },
  {
    id: "p12",
    role: "parachute",
    level: 3,
    title: "下属摸鱼",
    situation: "你发现一名老员工长期低效但态度不错。",
    options: ["直接警告", "先1对1了解真实原因", "调岗", "公开批评"],
    best: 1,
    feedback: "先诊断是能力、意愿还是系统问题，再决定动作。",
    knowledge: "绩效诊断"
  },
  {
    id: "p13",
    role: "parachute",
    level: 4,
    title: "跨部门抢资源",
    situation: "市场部说资源已投入别的项目，你的项目时间紧迫。",
    options: ["向经理上报", "提出每周少量关键投入", "切出最小依赖项", "找高层压人"],
    best: 2,
    feedback: "精确切割依赖项，把资源争夺变成精准协作。",
    knowledge: "跨部门协作"
  },
  {
    id: "p14",
    role: "parachute",
    level: 4,
    title: "骨干争功",
    situation: "两个骨干为同一个项目争功，公开场合互不相让。",
    options: ["各打五十大板", "把功劳变成共同成果并明确分工", "偏袒能力强的一方", "让上级仲裁"],
    best: 1,
    feedback: "把竞争转化为共同目标，功劳归属用成果说话。",
    knowledge: "协作能力"
  },
  {
    id: "p15",
    role: "parachute",
    level: 4,
    title: "新老冲突",
    situation: "新人提了新做法，老员工觉得不靠谱，双方开始对立。",
    options: ["站新人", "站老员工", "组织一次围绕数据和风险的联合复盘", "让他们自己解决"],
    best: 2,
    feedback: "用事实和风险对话，把对立变成共同验证。",
    knowledge: "冲突管理"
  },
  {
    id: "p16",
    role: "parachute",
    level: 4,
    title: "客户投诉交付",
    situation: "客户当众质疑团队交付能力，团队士气受挫。",
    options: ["当场反驳", "承接问题并给验证时间", "承诺不可能的时间", "让下属去处理"],
    best: 1,
    feedback: "对外稳住局面，对内保护团队尊严。",
    knowledge: "危机沟通"
  },
  {
    id: "p17",
    role: "parachute",
    level: 5,
    title: "上级要快速见效",
    situation: "上级希望三个月看到明显业绩变化，但团队基础薄弱。",
    options: ["承诺激进目标", "先对齐成功标准再排优先级", "先做面子工程", "拒绝上级"],
    best: 1,
    feedback: "用清晰的标准和优先级管理预期，而不是空头承诺。",
    knowledge: "预期管理"
  },
  {
    id: "p18",
    role: "parachute",
    level: 5,
    title: "项目延期",
    situation: "关键项目确定延期，客户和上级都在追问。",
    options: ["隐瞒到最后一刻", "主动同步并给出恢复方案", "责怪团队", "要求加班"],
    best: 1,
    feedback: "主动报告坏消息并带方案，是建立信任的证据。",
    knowledge: "责任担当"
  },
  {
    id: "p19",
    role: "parachute",
    level: 5,
    title: "核心成员想离职",
    situation: "技术骨干收到竞对offer，理由是工作重复没挑战。",
    options: ["加薪硬留", "了解真实原因并设计成长路径", "直接放人", "让他带人交接"],
    best: 1,
    feedback: "先搞清楚是钱、成长还是信任问题，再决定挽留方式。",
    knowledge: "人才保留"
  },
  {
    id: "p20",
    role: "parachute",
    level: 5,
    title: "被要求裁人",
    situation: "公司要求裁掉团队20%，你刚上任不久。",
    options: ["按名单执行", "先复盘业务优先级再提保留建议", "拒绝执行", "让HR背锅"],
    best: 1,
    feedback: "用业务优先级说话，把裁员变成组织瘦身决策。",
    knowledge: "组织决策"
  },
  {
    id: "p21",
    role: "parachute",
    level: 6,
    title: "前任消极对抗",
    situation: "前任开始消极配合，关键信息不再主动同步。",
    options: ["公开批评", "再次1对1并给他发展承诺", "架空他", "向团队揭露"],
    best: 1,
    feedback: "把前任变成军师和信息源头，比对抗更有价值。",
    knowledge: "关系管理"
  },
  {
    id: "p22",
    role: "parachute",
    level: 6,
    title: "越级汇报",
    situation: "有人绕过你直接向上一级汇报，你从别人口中得知。",
    options: ["公开警告", "先了解动机再一对一对齐边界", "也越级告状", "忽略"],
    best: 1,
    feedback: "先诊断是信任问题还是流程问题，再对齐边界。",
    knowledge: "组织边界"
  },
  {
    id: "p23",
    role: "parachute",
    level: 6,
    title: "会议无结论",
    situation: "每次会议都在对齐信息，但总不出决策。",
    options: ["继续开大会", "区分过程导向和任务导向会议", "取消会议", "让所有人书面发言"],
    best: 1,
    feedback: "任务导向会议控制人数并产出决策，过程会议规律化。",
    knowledge: "会议管理"
  },
  {
    id: "p24",
    role: "parachute",
    level: 6,
    title: "目标模糊",
    situation: "公司给了团队一个模糊年度目标，成员不知道做什么。",
    options: ["等公司明确", "把模糊目标翻译成可验证KR", "自己定目标", "让HR解释"],
    best: 1,
    feedback: "把模糊愿景拆成3-5个要务和可量化关键结果。",
    knowledge: "目标管理"
  },
  {
    id: "p25",
    role: "parachute",
    level: 7,
    title: "推行OKR受阻",
    situation: "上级要求推行OKR，团队觉得又是形式主义。",
    options: ["直接要求填表", "先讲为什么对齐再试点", "让团队自己决定", "先不推"],
    best: 1,
    feedback: "先讲目的和收益，再试点让团队看到价值。",
    knowledge: "OKR落地"
  },
  {
    id: "p26",
    role: "parachute",
    level: 7,
    title: "挑战目标",
    situation: "团队不愿接受挑战性目标，担心完不成被罚。",
    options: ["降低目标", "说明70%完成率算成功并给安全空间", "强制接受", "换团队"],
    best: 1,
    feedback: "挑战性目标需要安全感和失败容忍度。",
    knowledge: "驱动力"
  },
  {
    id: "p27",
    role: "parachute",
    level: 7,
    title: "你成为瓶颈",
    situation: "所有关键决策都要你拍板，团队开始等你。",
    options: ["继续自己决策", "列出可授权任务并分级", "让团队猜", "减少决策"],
    best: 1,
    feedback: "把只有你能做的事拆解，先授权30%。",
    knowledge: "授权阶梯"
  },
  {
    id: "p28",
    role: "parachute",
    level: 7,
    title: "授权后犯错",
    situation: "你把任务授权给骨干，他犯了一个可控但明显的错。",
    options: ["收回授权", "复盘原因并继续培养", "当众批评", "让他写检讨"],
    best: 1,
    feedback: "允许犯错但控制损失，授权和培养需要安全失败空间。",
    knowledge: "授权管理"
  },
  {
    id: "p29",
    role: "parachute",
    level: 8,
    title: "培养对象成长慢",
    situation: "你花时间培养的骨干进步不明显，你开始怀疑。",
    options: ["放弃他", "诊断是意愿还是能力问题并调整任务", "给他更多琐事", "换人"],
    best: 1,
    feedback: "先诊断瓶颈，再针对性派活补短板。",
    knowledge: "梯队诊断"
  },
  {
    id: "p30",
    role: "parachute",
    level: 8,
    title: "向上汇报梯队",
    situation: "上级要求你汇报梯队建设进展，你只有模糊计划。",
    options: ["讲投入感", "用具体证据：谁独立交付了什么", "画大饼", "让HR代答"],
    best: 1,
    feedback: "梯队建设要讲动作和可验证结果，而不是投入感。",
    knowledge: "接班汇报"
  },
  {
    id: "p31",
    role: "parachute",
    level: 8,
    title: "下属公开质疑",
    situation: "资深成员在会议上公开质疑你的管理决定。",
    options: ["当场反驳", "邀请他做风险识别者并保留决策节奏", "立即改方向", "会后冷处理"],
    best: 1,
    feedback: "倾听而不让步，把质疑转化为执行保障。",
    knowledge: "领导力试炼"
  },
  {
    id: "p32",
    role: "parachute",
    level: 8,
    title: "上级要求改变团队方向",
    situation: "上级要求调整团队方向，但会破坏团队现有节奏。",
    options: ["直接反对", "私下提供数据和建议后再执行", "表面答应背后不做", "越级沟通"],
    best: 1,
    feedback: "先对齐信息，用事实影响上级，再在执行中保留反馈通道。",
    knowledge: "跨层对齐"
  },
  {
    id: "p33",
    role: "parachute",
    level: 9,
    title: "文化不适",
    situation: "公司文化与你的习惯不同，团队期待你适应旧文化。",
    options: ["强制推行新文化", "先理解旧文化再小步调整", "完全融入旧文化", "抱怨"],
    best: 1,
    feedback: "文化变革需要先理解再小步调整，不能一步到位。",
    knowledge: "文化变革"
  },
  {
    id: "p34",
    role: "parachute",
    level: 9,
    title: "i人做团建",
    situation: "团队期待团建拉近距离，而你性格偏内向。",
    options: ["硬着头皮搞大型团建", "用固定1对1和书面同步建立连接", "拒绝团建", "让HR负责"],
    best: 1,
    feedback: "高质沟通比高频社交更适合i人管理者。",
    knowledge: "i人管理"
  },
  {
    id: "p35",
    role: "parachute",
    level: 9,
    title: "绩效评估",
    situation: "你需要给一个绩效差但态度好的下属做评估。",
    options: ["直接打低分", "先摆事实再谈差距和改善计划", "给高分避免冲突", "让HR处理"],
    best: 1,
    feedback: "绩效反馈要具体、可验证，并落到改善行动。",
    knowledge: "绩效管理"
  },
  {
    id: "p36",
    role: "parachute",
    level: 9,
    title: "离开前交接",
    situation: "你准备升任更高岗位，需要确保部门离开你能运转。",
    options: ["把关键事继续留给自己", "确认两位接班人并做交接演练", "只口头交代", "让上级指定"],
    best: 1,
    feedback: "领导者的长久价值由继承者决定，交接要可验证。",
    knowledge: "传承"
  }
];
