import type { AcademyScenario } from "./team-academy";

export const HIGH_POTENTIAL_SCENARIOS: AcademyScenario[] = [
  {
    id: "h1",
    role: "highPotential",
    level: 1,
    title: "第一周的基础任务",
    situation: "新入职第一周，经理让你先整理项目文档并熟悉流程。",
    options: ["按流程完成即可", "完成后再做一份带判断的摘要", "直接要求核心任务", "先私下打听晋升路径"],
    best: 1,
    feedback: "在基础任务上叠加判断和附加值，是训练模式里最稳的起步。",
    knowledge: "执行深度"
  },
  {
    id: "h2",
    role: "highPotential",
    level: 1,
    title: "认识团队成员",
    situation: "你刚加入团队，成员之间有默契但你还不知道各自分工。",
    options: ["等别人主动介绍", "约每人20分钟了解职责和痛点", "只看组织架构图", "先做自己的事"],
    best: 1,
    feedback: "主动建立信息地图，是快速融入团队的第一步。",
    knowledge: "关系建立"
  },
  {
    id: "h3",
    role: "highPotential",
    level: 1,
    title: "非核心项目",
    situation: "你被分配到一个边缘项目，成长空间有限。",
    options: ["拒绝并争取核心项目", "把边缘项目做出可复用成果", "应付了事", "直接找高层换项目"],
    best: 1,
    feedback: "把边缘任务变成可复用成果，是积累可见度的重要方式。",
    knowledge: "专业态度"
  },
  {
    id: "h4",
    role: "highPotential",
    level: 1,
    title: "了解团队目标",
    situation: "你还不清楚团队本季度的核心目标，也不知道自己该往哪使劲。",
    options: ["等周会再说", "主动找经理确认目标和优先级", "自己猜", "只做被安排的事"],
    best: 1,
    feedback: "主动对齐目标是减少返工和提升贡献的前提。",
    knowledge: "目标对齐"
  },
  {
    id: "h5",
    role: "highPotential",
    level: 2,
    title: "成果没被看到",
    situation: "你完成了一项改进，但经理和团队都不知道。",
    options: ["继续默默做", "在合适节点做简短成果同步", "逢人就说", "等绩效再展示"],
    best: 1,
    feedback: "有节奏的成果同步，比一次性的自我展示更自然。",
    knowledge: "可见度"
  },
  {
    id: "h6",
    role: "highPotential",
    level: 2,
    title: "会议发言被忽略",
    situation: "你在会上提出建议，但大家没有回应就跳过了。",
    options: ["不再发言", "会后把建议写成补充材料再同步", "提高音量打断", "私下抱怨"],
    best: 1,
    feedback: "书面补充比现场争夺注意力更容易被采纳。",
    knowledge: "影响力"
  },
  {
    id: "h7",
    role: "highPotential",
    level: 2,
    title: "主动汇报进展",
    situation: "项目进入关键期，经理忙于其他事务，很少主动问你。",
    options: ["等他来问", "每周做一次简短进展同步", "每天发消息", "不汇报"],
    best: 1,
    feedback: "固定节奏的主动汇报能降低经理的认知负担。",
    knowledge: "向上管理"
  },
  {
    id: "h8",
    role: "highPotential",
    level: 2,
    title: "帮同事救火",
    situation: "同事的项目即将延期，请求你帮忙，但你也有自己的任务。",
    options: ["直接拒绝", "确认自己任务优先级后提供有限支持", "全部接下", "让经理分配"],
    best: 1,
    feedback: "在保护自己产出的前提下提供支持，是成熟的协作方式。",
    knowledge: "协作边界"
  },
  {
    id: "h9",
    role: "highPotential",
    level: 3,
    title: "对上级方案有疑问",
    situation: "你发现上级提出的方案存在一个未被讨论的风险。",
    options: ["会议上直接指出", "会后私下用假设性语言反馈", "保持沉默", "先告诉同事"],
    best: 1,
    feedback: "私下反馈风险、公开支持决策，是向上管理的常见解法。",
    knowledge: "向上反馈"
  },
  {
    id: "h10",
    role: "highPotential",
    level: 3,
    title: "上级决策仓促",
    situation: "上级为了速度做了决定，但缺少风险分析。",
    options: ["照做", "提供一份补充风险分析", "反对决定", "等出事再提"],
    best: 1,
    feedback: "用补充分析帮助上级，而不是批评决策。",
    knowledge: "决策支持"
  },
  {
    id: "h11",
    role: "highPotential",
    level: 3,
    title: "模糊任务",
    situation: "上级交给你一个开放任务，没有明确标准和交付格式。",
    options: ["按自己理解做", "先确认目标和优先级", "拒绝", "拖到有人说明"],
    best: 1,
    feedback: "先澄清预期再执行，是高效工作者的习惯。",
    knowledge: "预期澄清"
  },
  {
    id: "h12",
    role: "highPotential",
    level: 3,
    title: "被要求加班",
    situation: "项目紧急，上级要求你连续加班，但你已经连续高强度工作。",
    options: ["无条件接受", "确认任务优先级并给出可持续方案", "直接拒绝", "隐瞒疲劳"],
    best: 1,
    feedback: "管理自己的能量也是职业化的一部分。",
    knowledge: "自我管理"
  },
  {
    id: "h13",
    role: "highPotential",
    level: 4,
    title: "没有头衔协调项目",
    situation: "你被指定协调一个跨职能项目，但没有正式授权。",
    options: ["要求头衔", "书面分工并公开同步", "自己全做", "等经理推动"],
    best: 1,
    feedback: "透明信息和共同承诺，比头衔更能推动执行。",
    knowledge: "横向影响力"
  },
  {
    id: "h14",
    role: "highPotential",
    level: 4,
    title: "同事不配合",
    situation: "一位资深同事对你的协调指令不以为然，进度被拖延。",
    options: ["找经理告状", "先了解他的顾虑再调整方式", "公开施压", "忽略"],
    best: 1,
    feedback: "先解决意愿，再解决进度。",
    knowledge: "关系管理"
  },
  {
    id: "h15",
    role: "highPotential",
    level: 4,
    title: "跨部门借资源",
    situation: "你的项目需要其他部门少量配合，但对方说没有资源。",
    options: ["要求对方全包", "切出最小依赖项", "直接找高层", "放弃"],
    best: 1,
    feedback: "把依赖切到最小，能显著降低协作门槛。",
    knowledge: "跨部门协作"
  },
  {
    id: "h16",
    role: "highPotential",
    level: 4,
    title: "提出流程改进",
    situation: "你发现流程可以优化，但经理担心占用团队时间。",
    options: ["放弃", "用自己的任务先做小试点", "私下找同事试点", "写长方案"],
    best: 1,
    feedback: "最小成本验证是推动变革的常见做法。",
    knowledge: "推动变革"
  },
  {
    id: "h17",
    role: "highPotential",
    level: 5,
    title: "建议执行不佳",
    situation: "你提出的改进执行后效果不如预期，团队开始质疑。",
    options: ["硬撑", "主动复盘并调整方案", "否认责任", "等被发现"],
    best: 1,
    feedback: "主动复盘比被动等待更能建立信任。",
    knowledge: "责任担当"
  },
  {
    id: "h18",
    role: "highPotential",
    level: 5,
    title: "被要求复盘",
    situation: "项目失败后，上级要求团队复盘，气氛紧张。",
    options: ["先找责任人", "先复盘系统流程", "只谈成绩", "沉默"],
    best: 1,
    feedback: "先系统后个人，复盘才有建设性。",
    knowledge: "复盘方法"
  },
  {
    id: "h19",
    role: "highPotential",
    level: 5,
    title: "缺少绩效反馈",
    situation: "你很久没有收到经理的具体反馈，不确定方向对不对。",
    options: ["等年度评估", "主动约1对1请求反馈", "猜", "换个部门"],
    best: 1,
    feedback: "主动请求反馈，能减少方向不确定性。",
    knowledge: "反馈获取"
  },
  {
    id: "h20",
    role: "highPotential",
    level: 5,
    title: "同事获得晋升",
    situation: "和你同期的人获得晋升，你觉得自己成果不差。",
    options: ["质疑决定", "问经理差距并制定计划", "直接离职", "只祝贺"],
    best: 1,
    feedback: "把失利转成改进清单，比情绪更重要。",
    knowledge: "成长心态"
  },
  {
    id: "h21",
    role: "highPotential",
    level: 6,
    title: "参加培训项目",
    situation: "你被选中参加培养项目，但担心影响当前业务。",
    options: ["全情投入", "和经理确认时间平衡", "只当任务", "拒绝"],
    best: 1,
    feedback: "提前对齐投入边界，才能兼顾成长与产出。",
    knowledge: "发展管理"
  },
  {
    id: "h22",
    role: "highPotential",
    level: 6,
    title: "导师建议冲突",
    situation: "导师建议你横向发展，经理希望你纵向深耕。",
    options: ["听导师", "听经理", "整合成阶段性路径", "都不听"],
    best: 2,
    feedback: "把两条建议组合成先后次序，而不是选边。",
    knowledge: "职业规划"
  },
  {
    id: "h23",
    role: "highPotential",
    level: 6,
    title: "兴趣方向变化",
    situation: "你对当前方向兴趣下降，更想转向另一个领域。",
    options: ["隐藏", "在1对1坦诚表达", "立刻转岗", "抱怨"],
    best: 1,
    feedback: "坦诚表达能让组织帮你规划过渡。",
    knowledge: "自我认知"
  },
  {
    id: "h24",
    role: "highPotential",
    level: 6,
    title: "高难度任务",
    situation: "上级把一个很难的任务交给你，成功概率不高。",
    options: ["硬扛", "接受并说明所需支持", "拒绝", "先接下再拖"],
    best: 1,
    feedback: "管理完成条件比赌运气更职业。",
    knowledge: "资源管理"
  },
  {
    id: "h25",
    role: "highPotential",
    level: 7,
    title: "高潜标签被疏远",
    situation: "被贴上高潜标签后，同事和你交流变得拘谨。",
    options: ["不在意", "分享真实盲区拉近距离", "刻意表现平庸", "疏远回去"],
    best: 1,
    feedback: "真实示弱能平衡身份带来的距离感。",
    knowledge: "关系平衡"
  },
  {
    id: "h26",
    role: "highPotential",
    level: 7,
    title: "与资深同事合作",
    situation: "你需要和一位经验丰富的同事合作，但他有自己的方式。",
    options: ["坚持你的方式", "先请教他的经验再谈方案", "完全听他的", "绕过他"],
    best: 1,
    feedback: "把资历差异变成互补，而不是对立。",
    knowledge: "协作"
  },
  {
    id: "h27",
    role: "highPotential",
    level: 7,
    title: "新领导空降",
    situation: "团队换了新领导，你还不了解他的风格和期待。",
    options: ["观望", "主动约1对1建立连接", "只汇报结果", "等安排"],
    best: 1,
    feedback: "空降期主动建立连接，容易获得首批信任。",
    knowledge: "向上管理"
  },
  {
    id: "h28",
    role: "highPotential",
    level: 7,
    title: "工作边界模糊",
    situation: "你的职责不断扩展，但岗位和薪资没有变化。",
    options: ["全部接受", "和经理确认定位与优先级", "直接拒绝", "默默记录"],
    best: 1,
    feedback: "管理边界是职业化管理的一部分。",
    knowledge: "边界管理"
  },
  {
    id: "h29",
    role: "highPotential",
    level: 8,
    title: "晋升等待",
    situation: "经理说你够资格，但需要再等下一批名额。",
    options: ["被动等", "问差距并补证据", "换工作", "找关系"],
    best: 1,
    feedback: "等待期变成准备期，是晋升准备的关键。",
    knowledge: "晋升准备"
  },
  {
    id: "h30",
    role: "highPotential",
    level: 8,
    title: "模糊晋升信号",
    situation: "经理说你应该为下一级别做准备，但没有清单。",
    options: ["默默等", "追问具体差距", "盲目承担任务", "不当回事"],
    best: 1,
    feedback: "把模糊信号转成具体行动。",
    knowledge: "信号转化"
  },
  {
    id: "h31",
    role: "highPotential",
    level: 8,
    title: "功劳被冒认",
    situation: "你的成果被同事在公开场合当作自己的贡献。",
    options: ["公开指正", "私下确认并请经理校准", "沉默", "写匿名信"],
    best: 1,
    feedback: "温和维护归属，比对抗更有效。",
    knowledge: "贡献归属"
  },
  {
    id: "h32",
    role: "highPotential",
    level: 8,
    title: "为他人做嫁衣",
    situation: "你被安排支持同事的高可见度汇报，荣誉不归你。",
    options: ["只做事", "接受并争取支持角色可见度", "拒绝", "抢功"],
    best: 1,
    feedback: "支持他人时也可以让自己被看见。",
    knowledge: "协作可见度"
  },
  {
    id: "h33",
    role: "highPotential",
    level: 9,
    title: "第一次带项目",
    situation: "你第一次负责一个完整项目，团队成员有不同资历。",
    options: ["自己扛所有关键决策", "先对齐目标再分工", "只当协调员", "等经理指导"],
    best: 1,
    feedback: "第一次带项目先对齐目标，是管理转型的起点。",
    knowledge: "领导转型"
  },
  {
    id: "h34",
    role: "highPotential",
    level: 9,
    title: "带新人",
    situation: "你需要辅导一位新人，同时保持自己的交付。",
    options: ["最低限度带", "制定成长计划并固定辅导", "推给别人", "只安排琐事"],
    best: 1,
    feedback: "可衡量的成长计划是培养能力的最好证据。",
    knowledge: "人才培养"
  },
  {
    id: "h35",
    role: "highPotential",
    level: 9,
    title: "公开质疑",
    situation: "你在推行新做法时，资深成员当众质疑。",
    options: ["当场反驳", "邀请他参与验证并说明节奏", "立刻让步", "冷处理"],
    best: 1,
    feedback: "倾听而不让步，是第一次领导试炼的关键。",
    knowledge: "领导力试炼"
  },
  {
    id: "h36",
    role: "highPotential",
    level: 9,
    title: "离开前的交接",
    situation: "你要转岗或升任，需要把当前工作交接给团队。",
    options: ["留关键事给自己", "写交接清单并培训接手人", "口头交代", "直接离开"],
    best: 1,
    feedback: "可验证的交接是责任感的体现。",
    knowledge: "交接传承"
  }
];
