import type { AcademyScenario } from "./team-academy";

export const HIGH_POTENTIAL_SCENARIOS: AcademyScenario[] = [
  {
    id: "h1",
    role: "highPotential",
    level: 1,
    title: "第一次给团队分工",
    situation: "你被指定牵头一个新项目，但没有正式头衔，需要给5位成员分工。",
    options: ["按熟悉度随意分配", "先了解每个人的能力与负载再分工", "谁离得近就交给谁", "自己承担大部分任务"],
    best: 1,
    feedback: "团队分工要基于能力、负载和目标，而不是关系或距离。",
    knowledge: "任务分配"
  },
  {
    id: "h2",
    role: "highPotential",
    level: 1,
    title: "对齐团队目标",
    situation: "团队对项目目标理解不一致，有人想做功能，有人想做质量。",
    options: ["按自己的理解推进", "先开会把目标和验收标准对齐", "让每个人按自己理解做", "让经理定"],
    best: 1,
    feedback: "目标不对齐，分工越细越混乱。",
    knowledge: "目标对齐"
  },
  {
    id: "h3",
    role: "highPotential",
    level: 1,
    title: "任务优先级冲突",
    situation: "多个成员同时向你提出需要先做自己的任务，但资源有限。",
    options: ["按声音大的人优先", "用损失最大原则排序", "全部都要做", "抽签决定"],
    best: 1,
    feedback: "资源有限时，用业务损失排序比用情绪排序更稳。",
    knowledge: "优先级"
  },
  {
    id: "h4",
    role: "highPotential",
    level: 1,
    title: "成员职责不清",
    situation: "团队里有人重复做同一件事，另一件事却没人负责。",
    options: ["等出了问题再说", "重画职责矩阵并公开确认", "让资历深的人全包", "只提醒一个人"],
    best: 1,
    feedback: "职责不清时要显式化分工，而不是靠默契。",
    knowledge: "职责明确"
  },
  {
    id: "h5",
    role: "highPotential",
    level: 2,
    title: "第一次项目会议",
    situation: "项目启动会开了40分钟，还在讨论背景，没有人说下一步。",
    options: ["继续讨论到大家明白", "把会切成信息同步和决策两部分", "直接散会", "让经理主持"],
    best: 1,
    feedback: "启动会要快速从背景转向决策和行动项。",
    knowledge: "会议管理"
  },
  {
    id: "h6",
    role: "highPotential",
    level: 2,
    title: "会议出不了结论",
    situation: "每次周会都在对齐，但总是定不下下一步。",
    options: ["开更长的会", "会前给议题和决策项，会中定行动人", "取消周会", "让所有人书面发言"],
    best: 1,
    feedback: "决策会议要带着议题、选项和行动人来开。",
    knowledge: "会议产出"
  },
  {
    id: "h7",
    role: "highPotential",
    level: 2,
    title: "跨部门协作卡住",
    situation: "项目需要另一个部门配合，但对方说排期已满。",
    options: ["找对方领导施压", "把依赖切到最小并说明价值", "等对方有空", "自己偷偷做"],
    best: 1,
    feedback: "把跨部门依赖切到最小，是推进协作的关键。",
    knowledge: "跨部门协作"
  },
  {
    id: "h8",
    role: "highPotential",
    level: 2,
    title: "团队资源不足",
    situation: "任务量超过团队容量，你无法满足所有交付承诺。",
    options: ["全员加班", "重新排序并向上确认可砍项", "硬接所有需求", "让客户自己排序"],
    best: 1,
    feedback: "容量不足时，管理预期和排序比硬扛更重要。",
    knowledge: "资源管理"
  },
  {
    id: "h9",
    role: "highPotential",
    level: 3,
    title: "给成员反馈",
    situation: "一名成员交付质量不错，但总是延迟，团队节奏被拖慢。",
    options: ["只在交付时提醒", "1对1说明延迟影响并约定检查节点", "公开批评", "换人"],
    best: 1,
    feedback: "反馈要具体、及时，并落到检查和改善行动。",
    knowledge: "绩效反馈"
  },
  {
    id: "h10",
    role: "highPotential",
    level: 3,
    title: "成员犯了错",
    situation: "成员在交付中犯了一个影响客户信任的错误。",
    options: ["追责", "先修复再复盘系统原因", "隐瞒", "让HR处理"],
    best: 1,
    feedback: "先止损再复盘，复盘面向系统而非个人。",
    knowledge: "错误处理"
  },
  {
    id: "h11",
    role: "highPotential",
    level: 3,
    title: "成员之间冲突",
    situation: "两名成员因方案分歧开始互相指责，会议氛围变差。",
    options: ["让双方各自冷静", "把分歧变成可验证的对比实验", "站一边", "终止合作"],
    best: 1,
    feedback: "用数据和实验解决分歧，而不是用立场。",
    knowledge: "冲突管理"
  },
  {
    id: "h12",
    role: "highPotential",
    level: 3,
    title: "新老成员矛盾",
    situation: "新人提出新做法，老员工觉得不靠谱，双方开始对立。",
    options: ["偏袒老员工", "围绕风险和证据做联合复盘", "偏袒新人", "让他们自己解决"],
    best: 1,
    feedback: "让双方围绕事实和风险对话，而不是站队。",
    knowledge: "团队融合"
  },
  {
    id: "h13",
    role: "highPotential",
    level: 4,
    title: "成员情绪低落",
    situation: "一位核心成员最近状态很差，交付质量下降，但不说原因。",
    options: ["等他自己好", "1对1了解原因并给支持", "直接调岗", "公开提醒"],
    best: 1,
    feedback: "先了解情绪背后的原因，再决定支持方式。",
    knowledge: "情绪管理"
  },
  {
    id: "h14",
    role: "highPotential",
    level: 4,
    title: "团队没有激情",
    situation: "团队能完成任务，但不再主动提想法，像在交差。",
    options: ["加奖金", "给更多自主权和意义感", "开会打鸡血", "换人"],
    best: 1,
    feedback: "自主、专精、目的是驱动团队内驱力的三要素。",
    knowledge: "团队激励"
  },
  {
    id: "h15",
    role: "highPotential",
    level: 4,
    title: "目标太模糊",
    situation: "上级给了你一个模糊目标，团队不知道做什么才算完成。",
    options: ["让团队自己猜", "把模糊目标拆成可验证KR", "按经验做", "等上级细化"],
    best: 1,
    feedback: "模糊目标要翻译成可验证的关键结果。",
    knowledge: "目标管理"
  },
  {
    id: "h16",
    role: "highPotential",
    level: 4,
    title: "计划不执行",
    situation: "团队同意了计划，但执行时总打折扣，进度落后。",
    options: ["批评执行力", "检查目标是否对齐、KR是否可量化", "换人", "每天催"],
    best: 1,
    feedback: "执行偏差常来自目标不清晰，而不是态度。",
    knowledge: "执行管理"
  },
  {
    id: "h17",
    role: "highPotential",
    level: 5,
    title: "远程协作不同步",
    situation: "团队部分成员远程工作，信息经常错过，进度不可见。",
    options: ["要求每天汇报", "建立异步文档和固定同步节奏", "取消远程", "靠自觉"],
    best: 1,
    feedback: "远程团队要靠透明文档和固定节奏，而不是控制。",
    knowledge: "远程协作"
  },
  {
    id: "h18",
    role: "highPotential",
    level: 5,
    title: "带新人上手",
    situation: "团队加入一位新人，需要快速上手，但没人愿意花时间带。",
    options: ["让新人自己摸索", "制定30天成长计划并固定辅导", "只给文档", "让最忙的人带"],
    best: 1,
    feedback: "新人的成长要有可验证的计划和辅导节奏。",
    knowledge: "新人辅导"
  },
  {
    id: "h19",
    role: "highPotential",
    level: 5,
    title: "老员工带新人",
    situation: "你请老员工辅导新人，老员工觉得耽误自己产出。",
    options: ["强制安排", "把辅导写进目标并减轻其他任务", "让新人自学", "放弃"],
    best: 1,
    feedback: "把辅导变成目标的一部分，老员工才愿意投入。",
    knowledge: "人才培养"
  },
  {
    id: "h20",
    role: "highPotential",
    level: 5,
    title: "授权给骨干",
    situation: "你负责的项目里有一名骨干能力很强，但你总忍不住检查每个细节。",
    options: ["继续全控", "按授权阶梯逐步放权", "完全放手", "让经理授权给他"],
    best: 1,
    feedback: "授权要按能力阶梯推进，既放权又保留检查节点。",
    knowledge: "授权管理"
  },
  {
    id: "h21",
    role: "highPotential",
    level: 6,
    title: "授权后犯错",
    situation: "你把任务授权给骨干，他在一个关键节点犯了可控的错。",
    options: ["收回授权", "复盘原因并继续培养", "公开批评", "让他写检讨"],
    best: 1,
    feedback: "授权需要安全失败空间，复盘比惩罚重要。",
    knowledge: "授权复盘"
  },
  {
    id: "h22",
    role: "highPotential",
    level: 6,
    title: "你成为团队瓶颈",
    situation: "所有关键决策都要经过你，团队开始停下来等你。",
    options: ["继续自己决策", "建立决策边界和授权规则", "减少决策", "让团队猜"],
    best: 1,
    feedback: "把决策权分级下放，是团队提效的关键。",
    knowledge: "决策机制"
  },
  {
    id: "h23",
    role: "highPotential",
    level: 6,
    title: "核心成员想离职",
    situation: "团队最核心的成员提出离职，理由是成长空间不够。",
    options: ["加薪硬留", "了解真实原因并设计成长路径", "直接放人", "签竞业"],
    best: 1,
    feedback: "先搞清楚是钱、成长还是信任，再决定挽留方式。",
    knowledge: "人才保留"
  },
  {
    id: "h24",
    role: "highPotential",
    level: 6,
    title: "人才盘点",
    situation: "你要为项目做人才盘点，但手上只有大家的表现印象。",
    options: ["凭印象排", "用业绩与潜力两维画九宫格", "只看资历", "让HR代做"],
    best: 1,
    feedback: "人才盘点要基于可验证的业绩与潜力，而不是印象。",
    knowledge: "人才盘点"
  },
  {
    id: "h25",
    role: "highPotential",
    level: 7,
    title: "培养接班人",
    situation: "你发现项目离开你难以运转，决定培养能接替你的人。",
    options: ["继续自己扛", "选2-3名高潜给完整小项目", "等有空再培养", "只给琐事"],
    best: 1,
    feedback: "培养接班人要从完整小项目和授权开始。",
    knowledge: "梯队建设"
  },
  {
    id: "h26",
    role: "highPotential",
    level: 7,
    title: "接班人犯错",
    situation: "你培养的接班人做了一个大决策，结果损失不小。",
    options: ["收回授权", "复盘系统并继续培养", "公开批评", "换人"],
    best: 1,
    feedback: "控制损失范围，把错误变成成长材料。",
    knowledge: "培养风险"
  },
  {
    id: "h27",
    role: "highPotential",
    level: 7,
    title: "绩效沟通",
    situation: "你需要和一位绩效一般的成员谈改进，担心伤害关系。",
    options: ["给高分避免冲突", "摆事实谈差距并约定改善计划", "直接打低分", "让HR谈"],
    best: 1,
    feedback: "绩效沟通要具体、可验证，并落到改善行动。",
    knowledge: "绩效管理"
  },
  {
    id: "h28",
    role: "highPotential",
    level: 7,
    title: "调整分工",
    situation: "项目中期发现分工不合理，有人过载有人闲置。",
    options: ["维持原分工", "重排分工并公开说明理由", "只调整过载的人", "让成员自己换"],
    best: 1,
    feedback: "重排分工要透明说明依据，避免被误解为针对个人。",
    knowledge: "团队调配"
  },
  {
    id: "h29",
    role: "highPotential",
    level: 8,
    title: "建立团队文化",
    situation: "团队开始出现甩锅文化，出了问题先找别人责任。",
    options: ["开会强调别甩锅", "把复盘改成先系统后个人", "惩罚甩锅者", "忽略"],
    best: 1,
    feedback: "文化要靠流程和复盘机制塑造，而不是口号。",
    knowledge: "团队文化"
  },
  {
    id: "h30",
    role: "highPotential",
    level: 8,
    title: "团队氛围变冷",
    situation: "项目压力大，团队交流变少，只剩下任务对接。",
    options: ["等压力过去", "安排一次非正式交流并降低威胁感", "要求大家热情", "换人"],
    best: 1,
    feedback: "氛围重建需要降低威胁感，而不是表演热情。",
    knowledge: "团队氛围"
  },
  {
    id: "h31",
    role: "highPotential",
    level: 8,
    title: "有人越级沟通",
    situation: "团队成员绕过你直接向经理汇报问题，你从别人口中得知。",
    options: ["公开警告", "先了解动机再对齐沟通边界", "也向经理告状", "忽略"],
    best: 1,
    feedback: "先诊断是信任还是流程问题，再对齐边界。",
    knowledge: "团队边界"
  },
  {
    id: "h32",
    role: "highPotential",
    level: 8,
    title: "信息不透明",
    situation: "团队成员掌握的信息不一致，决策经常基于残缺信息。",
    options: ["只让核心圈知道", "建立共享信息库和同步机制", "谁问告诉谁", "等出问题再补"],
    best: 1,
    feedback: "信息透明能减少重复解释和错误决策。",
    knowledge: "信息管理"
  },
  {
    id: "h33",
    role: "highPotential",
    level: 9,
    title: "项目交接",
    situation: "项目进行到一半，你要被调到新项目，需要交接给团队。",
    options: ["口头交代", "写交接清单并培训接手人", "留关键事给自己", "直接离开"],
    best: 1,
    feedback: "可验证的交接是团队稳定运转的保障。",
    knowledge: "交接管理"
  },
  {
    id: "h34",
    role: "highPotential",
    level: 9,
    title: "团队危机",
    situation: "项目突然延期，客户施压，团队开始互相指责。",
    options: ["先追责", "先止损再分团队复盘", "隐瞒", "让经理出面"],
    best: 1,
    feedback: "危机时先稳住团队，再系统复盘。",
    knowledge: "危机管理"
  },
  {
    id: "h35",
    role: "highPotential",
    level: 9,
    title: "公开质疑你的管理",
    situation: "你推行新的任务机制，资深成员当众质疑行不通。",
    options: ["当场反驳", "邀请他参与验证并说明节奏", "立即取消", "冷处理"],
    best: 1,
    feedback: "倾听而不让步，把质疑变成共同验证。",
    knowledge: "管理权威"
  },
  {
    id: "h36",
    role: "highPotential",
    level: 9,
    title: "第一次带团队",
    situation: "你第一次正式带团队，需要从同事关系切换到管理关系。",
    options: ["和以前一样", "先对齐目标、分工和反馈机制", "只发指令", "等出问题再管"],
    best: 1,
    feedback: "第一次带团队要先立目标和协作机制，而不是表演权威。",
    knowledge: "管理转型"
  }
];
